/**
 * Opis znaka sa astroshop.rs/znak/<znak>/ (tekst astrologa sa sajta, javan) — za PRICU O ZNAKU
 * (pravilo 25). GENERISANO skriptom `scripts/znak/pripremi.py`; ne menjati rucno, nego na sajtu
 * pa ponovo pokrenuti skriptu.
 *
 * Naslovi (`ukratko`, `ljubav`, `posao`) su deo naslova poglavlja posle dvotacke, `osvojiti` deo
 * naslova "Kako zavesti ..." posle upitnika, a `*Recenica` prva recenica poglavlja. Ispravljene su
 * samo slovne greske (spisak u skripti). Tekstovi su u trecem licu i mestimicno u "Vi" obliku —
 * kako ih je astrolog napisao.
 */
export type ZnakOpis = {
  ukratko: string;
  ukratkoRecenica: string;
  ljubav: string;
  ljubavRecenica: string;
  posao: string;
  posaoRecenica: string;
  osvojiti: string;
  vrednosti: string[];
  pol: string;
  izgled: string;
  telo: string;
  zivotinja: string;
  kamen: string;
  boja: string;
  biljka: string;
  hrana: string;
};

export const ZNAK_OPIS: Record<string, ZnakOpis> = {
  aries: {
    ukratko: "Otvorenost i ishitrenost",
    ukratkoRecenica: "Ovan je po prirodi velikodušan horoskopski znak, spreman da bezrezervno podeli svoje vreme, novac i trud.",
    ljubav: "Strastveni i aktivni ljubavnici",
    ljubavRecenica: "Zaljubljeni Ovan je izuzetno strastven i aktivan ljubavnik, i ne smeta mu da ljubav sagleda kako kroz pozitivna iskustva tako i kroz sopstvene greške.",
    posao: "Stalna aktivnost i odlična organizacija",
    posaoRecenica: "Ovan kao horoskopski znak generalno teži poslovima koji traže aktivnost i dobru organizaciju.",
    osvojiti: "Ovan želi da čuje sve o vašim divljim ambicijama!",
    vrednosti: ["Časnost", "Vernost", "Tačnost", "Odlučnost", "Vitalnost"],
    pol: "Muški",
    izgled: "Vitak, hoda kao da trči, brzi pokreti, svetla put, prozirne oči, kosa ima crvenkasti odsjaj na suncu, mladeži",
    telo: "Glava, lice, gornja vilica, jetra, hipofiza",
    zivotinja: "Ovca, ali posebno Ovan",
    kamen: "Dijamant",
    boja: "Crvena i ostale vatrene nijanse",
    biljka: "Amarilis, čičak, gujina trava, orlova kandža",
    hrana: "Začinjena i slana hrana",
  },
  taurus: {
    ukratko: "Hedonizam i taktičnost",
    ukratkoRecenica: "Taktičan i rezervisan, sa izraženom potrebom za materijalnom sigurnošću, ovaj horoskopski znak polako ali sigurno teži ispunjenju svih svojih želja.",
    ljubav: "Senzualni, atraktivni i romantični",
    ljubavRecenica: "Znakom Bika vlada planeta lepote Venera koja rado prihvata poklone čak i kad nije zaljubljena pa će Bikovi uvek biti senzualni, atraktivni i romantični.",
    posao: "Dobro baratanje novcem",
    posaoRecenica: "Bik se prema horoskopu dobro snalazi u bankarstvu i finansijama, tj. generalno u poslovima u vezi sa nekretninama i novcem.",
    osvojiti: "Bik želi da mu neko sprema hranu… Mnogo, mnogo hrane!",
    vrednosti: ["Postojanost", "Istrajnost"],
    pol: "Ženski",
    izgled: "Korpulentan, jaki mišići i široka ramena, mesnato lice, široko čelo, jak vrat, zemljana boja tena",
    telo: "Vrat, grlo, ždrelo, tiroida, jajnici, žlezde",
    zivotinja: "Bik",
    kamen: "Smaragd",
    boja: "Pink, pastelna plava i nežne nijanse zelene",
    biljka: "Ruža, mak, naprstak",
    hrana: "Mešavina aromatičnih začina",
  },
  gemini: {
    ukratko: "Vragolasti i svestrani",
    ukratkoRecenica: "Blizanci su socijalna bića, i horoskop ih je obdario sa visoko razvijenom veštinom komunikacije.",
    ljubav: "Intelektualna povezanost sa partnerom",
    ljubavRecenica: "Blizancima je ljubavni horoskop prvenstveno zasnovan na intelektualnoj povezanosti sa partnerom.",
    posao: "Višestruki izvori prihoda",
    posaoRecenica: "Zbog nemirme naravi, horoskop kaže da Blizanci često poseduju dva – ili čak više – izvora prihoda.",
    osvojiti: "Blizanci žele da ih čuvate – i zabavljate!",
    vrednosti: ["Brzina", "Svestranost", "Bistrina", "Spretnost"],
    pol: "Muški",
    izgled: "Izraženi zglobovi, nemiran pokret, prozračen ten, često nerazumljiv govor, nemirne oči",
    telo: "Ramena, ruke, šake, prsti, pluća, rebra, nervi",
    zivotinja: "Šarene ptice poput papagaja, raznobojni leptiri ali i majmuni koji su duhoviti i prepuni zabavnih trikova",
    kamen: "Plavi turmalin i agat",
    boja: "Žuta",
    biljka: "Lavanda, đurđevak",
    hrana: "Kari",
  },
  cancer: {
    ukratko: "Stidljivost i osećajnost",
    ukratkoRecenica: "Rakovi imaju urođenu sposobnost odličnog pamćenja detalja i događaja, pa drugima deluju beskompromisno iako se iza tvrdog oklopa krije nesigurna priroda.",
    ljubav: "Neprikosnoveni romantičari",
    ljubavRecenica: "Rak je najsentimentalniji od svih znakova, neprikosnoveni romantičar horoskopa koji je spreman da se žrtvuje zarad ljubavi.",
    posao: "Radoholici i ljubitelji starina",
    posaoRecenica: "Zainteresovani za sve o čemu drugi ljudi razmišljaju, Rakovi poseduju razvijenu maštu i to ih čini dobrim piscima, novinarima i političarima.",
    osvojiti: "Rak želi iskrene odgovore na sva svoja pitanja",
    vrednosti: ["Pamćenje", "Predusretljivost"],
    pol: "Ženski",
    izgled: "Masivna građa, tromi hod, vlažna koža, tamna put, vodnjikave oči, često skrivenog pogleda",
    telo: "Grudi, želudac, stomak, pankreas",
    zivotinja: "Rakovi obožavaju životinje koje imaju oklop poput školjki i ostalih mekušaca koji nose ljušturu sa sobom, baš kao što su i oni sami",
    kamen: "Biser i mesečev kamen",
    boja: "Srebrna i boje dima",
    biljka: "Ljiljan",
    hrana: "Peršun, ruzmarin, majčina dušica, žalfija",
  },
  leo: {
    ukratko: "Ambiciozni i neumoljivi",
    ukratkoRecenica: "Suštinski, Lavovi su jednostavne osobe koje uvek znaju šta žele.",
    ljubav: "Strastvena narav velikih apetita",
    ljubavRecenica: "Lav uvek mora biti dominantan a kad je ljubavni horoskop u pitanju to se podrazumeva jer je kralj Zodijaka nezavisni pojedinac sa izraženom seksualnim potencijalom.",
    posao: "Rođeni vođa",
    posaoRecenica: "Horoskop nalaže da jedan Lav uvek teži poziciji vođe.",
    osvojiti: "Lav želi nekog ko zna kako da mu se divi.",
    vrednosti: ["Vitalnost", "Savesnost", "Vernost", "Dostojanstvenost"],
    pol: "Muški",
    izgled: "Dostojanstveno držanje, razvijena ramena, odmeren i lagan hod, otvoren pogled, istaknut nos",
    telo: "Srce, kičma",
    zivotinja: "Lav kao kralj džungle obožava i druge članove iz porodice mačaka",
    kamen: "Rubin",
    boja: "Narandžasto-crvena",
    biljka: "Suncokret i ruzmarin",
    hrana: "Šafran",
  },
  virgo: {
    ukratko: "Marljivost, red i disciplina",
    ukratkoRecenica: "Device poseduju preciznu misao, kao i oštro oko za detalje.",
    ljubav: "Pedantni i brižni partneri",
    ljubavRecenica: "Devica važi za najpraktičniji znak u horoskopu a kad je ljubav u pitanju, ova praktičnost je nenadmašna.",
    posao: "Po prirodi perfekcionisti",
    posaoRecenica: "Device poseduju znatiželjan i logičan um, te su u tom smislu dobri učenici i nastavnici.",
    osvojiti: "Device žele nekoga sa kim će dugo razgovarati o emocijama",
    vrednosti: ["Humanost", "Ljubaznost", "Genijalnost"],
    pol: "Ženski",
    izgled: "Bojažljiv hod, zastajkuje dok hoda, sivkast ten, bistar pogled",
    telo: "Organi za varenje, abdomen, stomak, creva, pankreas",
    zivotinja: "Devica obožava sve domaće životinje, prvenstveno pse i mačke",
    kamen: "Sardoniks",
    boja: "Zelena i zemljani tonovi",
    biljka: "Ljutić, vučji jezik, narcis, hrizantema",
    hrana: "Anis",
  },
  libra: {
    ukratko: "Društvene, opuštene i neodlučne",
    ukratkoRecenica: "Kao ljubitelj lepote i sklada, kako u umetnosti, tako i u životu, Vaga je po horoskopu veoma nežna i ljubazna.",
    ljubav: "Prefinjeno i diskretno ponašanje",
    ljubavRecenica: "Vagom vlada planeta ljubavi Venera, zadužena za seksualna i čulna zadovoljstva.",
    posao: "Vešto rukuju tuđim novcem",
    posaoRecenica: "U profesionalnom domenu Vage se odlično snalaze kao advokati, antikvari, državni službenici i sudije.",
    osvojiti: "Vaga želi nekog ko će samo njoj biti posvećen",
    vrednosti: ["Harmoničnost", "Razumnost"],
    pol: "Muški",
    izgled: "Vitak, prozračna i nežna koža, lepi kapci, njiše se dok hoda, lep, često rupica na bradi",
    telo: "Bubrezi, jetra, leđa",
    zivotinja: "Zmije, gušteri i drugi mali reptili",
    kamen: "Safir",
    boja: "Plava i blede nijanse zelene",
    biljka: "Divlji zumbul, hrizantema, hortenzija",
    hrana: "Vanila",
  },
  scorpio: {
    ukratko: "Strasni, senzibilni i direktni",
    ukratkoRecenica: "Škorpioni se retko kad nalaze u centru zbivanja ali uvek znaju ono što ih zanima.",
    ljubav: "Strastveni predator",
    ljubavRecenica: "Kada je ljubavni horoskop u pitanju, Škorpion ulaže dosta energije u traganje za emotivnim partnerom.",
    posao: "Zanimanje za istraživanja i analize",
    posaoRecenica: "Škorpioni poseduju bujnu maštu i jaku intuiciju.",
    osvojiti: "Za Škorpiona važi: što strastvenije – to bolje",
    vrednosti: ["Upornost", "Hladnokrvnost", "Impulsivnost"],
    pol: "Ženski",
    izgled: "Korpulentne građe, tamna i suva kovrdžava kosa, čvrst hod, mladeži, privlačan",
    telo: "Reproduktivni organi, nos",
    zivotinja: "Insekti i drugi beskičmenjaci, od leptira do paukova i škorpija",
    kamen: "Opal",
    boja: "Bordo",
    biljka: "Gardenija, rododendron, zdravac",
    hrana: "Slačica",
  },
  sagittarius: {
    ukratko: "Jedinstvena kombinacija mudrosti i humora",
    ukratkoRecenica: "Strelčevi su, uprkos svojoj nestalnosti, obično skromni i duhovni ljudi sa izraženim vrednostima.",
    ljubav: "I prijatelj i ljubavnik",
    ljubavRecenica: "Strelac voli da stiče životna iskustva, a prilikom sticanja ljubavnog iskustva traži i druge kvalitete kod partnera.",
    posao: "Svestrani i radoznali",
    posaoRecenica: "Strelčevi su veliki mislioci i nadareni za predviđanje i dobre procene.",
    osvojiti: "Strelac želi veselu osobu sa smislom za humor",
    vrednosti: ["Tolerantnost", "Poštuju zakon", "Optimizam", "Idealizam"],
    pol: "Muški",
    izgled: "Lagan odmeren hod, poverljive, mirne oči, staloženost dok govore",
    telo: "Prepone i butine",
    zivotinja: "Jelen i ostala divljač",
    kamen: "Topaz",
    boja: "Ljubičasta",
    biljka: "Maslačak",
    hrana: "Cimet",
  },
  capricorn: {
    ukratko: "Siguran, jake volje i odgovoran",
    ukratkoRecenica: "Astrologija kaže da Jarac nikada nije žestok i da uvek staloženo i oprezno razmatra odnose i gotovo nikada ne daje savete, osim ako ih sami ne tražite.",
    ljubav: "Ljubav u radnom okruženju",
    ljubavRecenica: "Jarac ne haje mnogo za ljubavni horoskop tj. ne pridaje mu veliku važnost, jer kod njih uglavnom ljubav dolazi na red tek posle uspostavljanja karijere i životnog statusa.",
    posao: "Visoki standardi i za sebe i za druge",
    posaoRecenica: "Jarčevi imaju tedenciju da budu duboki mislioci.",
    osvojiti: "Jarac želi nekog ko zna da se ponaša u svakoj prilici",
    vrednosti: ["Lojalnost", "Odgovornost", "Izdržljivost"],
    pol: "Ženski",
    izgled: "Koščat, pažljiv hod, jak nos, zemljani ten, hladan pogled",
    telo: "Kosti, zubi, naročito kolena",
    zivotinja: "Koza i druge životinje sa kopitima",
    kamen: "Garnet",
    boja: "Sivo do crne, tamni tonovi",
    biljka: "Različak",
    hrana: "Pasulj",
  },
  aquarius: {
    ukratko: "Atraktivni i inteligentni vizionari",
    ukratkoRecenica: "Vodolije su dalekovide i inventivne, uglavnom bez predrasuda i prilično tolerantni u odnosu sa drugima.",
    ljubav: "Potreba za nezavisnošću",
    ljubavRecenica: "Od svih horoskopskih znakova Vodolija se najteže snalazi u održavanju emotivne veze.",
    posao: "Ljubitelji vodećih uloga",
    posaoRecenica: "Nezavisne po prirodi, Vodolije uživaju da poseduju sopstvenu kompaniju.",
    osvojiti: "Vodolija želi osobu koja se uključuje u debate",
    vrednosti: ["Originalnost", "Revolucionarnost", "Liberalnost"],
    pol: "Muški",
    izgled: "Uglavnom visokog rasta, privlačni, sa prozračnim tenom",
    telo: "Potkolenica, list i nervi",
    zivotinja: "Ptice koje su sposobne za let na duge udaljenosti kao što su albatrosi",
    kamen: "Akvamarin",
    boja: "Tirkizna",
    biljka: "Orhideja, zova, gladiola, rajska ptica",
    hrana: "Đumbir",
  },
  pisces: {
    ukratko: "Spoj svesnog i nesvesnog",
    ukratkoRecenica: "Ribe zbog svoje duple prirode u horoskopu predstavljaju realnost i nerealnost, svesno i nesvesno, prošlost i budućnost.",
    ljubav: "Najveći romantičari Zodijaka",
    ljubavRecenica: "Zbog svoje sanjalačke prirode, najfinije unutrašnje osećanje kao što je ljubav Ribe doživljavaju veoma intezivno.",
    posao: "Obožavaju kreativne poslove",
    posaoRecenica: "Ribe nisu naročito praktični ljudi horoskopa ali originalni i promenljivi svakako jesu.",
    osvojiti: "Ribe žele onog koji poseduje bajkovitu romantiku",
    vrednosti: ["Prijemčivost", "Prilagodljivost", "Ideologije"],
    pol: "Ženski",
    izgled: "Vodnjikave oči, podočnjaci, osetljiva koža",
    telo: "Stopala i limfni sistem",
    zivotinja: "Svaka životinja koja živi u vodi",
    kamen: "Ametist",
    boja: "Plavo-zeleni tonovi",
    biljka: "Beli vodeni ljiljan, lotus, jasmin",
    hrana: "Kakao",
  },
};
